version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gizchat_network

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - gizchat_network

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gizchat_network

volumes:
  mysql_data:

networks:
  gizchat_network:

